version: "3.7"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop-db
    ports:
      - '5432:5432'
    volumes:
      - shop-db:/var/lib/postgresql/data
      - ./src/migration/16-5-21-10-48-create-tables.sql:/docker-entrypoint-initdb.d/16-5-21-10-48-create-tables.sql
      - ./src/migration/16-5-21-12-01-bootstrap-data.sql:/docker-entrypoint-initdb.d/16-5-21-12-01-bootstrap-data.sql

  shop:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - '3000:3000'
      - '8080:8080'

volumes:
  shop-db:
